### ISSUE TITLE
About the output

### ISSUE THREAD

**Issue by JaneYul** [shuaiOKshuai/RALE#1]
Hi. Thank you for your codes.

When running 'python3 mainEntry.py' for test, the outputs of mean/stds/ci95 are 2-dim like 'mean: [0.49333334 0.8465423 ]'. What are their meanings?

**Comment by shuaiOKshuai** [comment]
Thank you for your interest. 
I remember the first dim is the accuracy for the support set (without any adaptation), while the second dim is the accuracy for the query set with one adaptation. If there are more following dimensions, then they mean the accuracy for the query set with the corresponding adaptations (i.e., the K+1 dim means the accuracy for the query set with K-th adaptation).

**Comment by shuaiOKshuai** [comment]
> Hi. Thank you for your codes.
> 
> When running 'python3 mainEntry.py' for test, the outputs of mean/stds/ci95 are 2-dim like 'mean: [0.49333334 0.8465423 ]'. What are their meanings?

Thank you for your interest.
I remember the first dim is the accuracy for the support set (without any adaptation), while the second dim is the accuracy for the query set with one adaptation. If there are more following dimensions, then they mean the accuracy for the query set with the corresponding adaptations (i.e., the K+1 dim means the accuracy for the query set with K-th adaptation).

**Comment by JaneYul** [comment]
Thank you for your explanation. :)
